name: Deploy to Altervista

on:
  pull_request:
    types: [closed]
  push:
    branches:
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Deploy via FTP
        env:
          FTP_HOST: ${{ secrets.ALTERVISTA_HOST }}
          FTP_USER: ${{ secrets.ALTERVISTA_USER }}
          FTP_PASSWORD: ${{ secrets.ALTERVISTA_PASSWORD }}
        run: |
          lftp -e "
            set ssl:verify-certificate no;
            set ftp:ssl-force true;
            set ftp:ssl-protect-data true;
            open -u $FTP_USER,$FTP_PASSWORD $FTP_HOST;
            mirror -R --delete --verbose \
              --include-glob '*.php' \
              --include-glob '*.css' \
              --include-glob '*.html' \
              --exclude-glob '.git/*' \
              --exclude-glob '.github/*' \
              ./ /;
            bye
          "
